# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 16267c4b4279e992f20189aff76c01da4bb3b3ef10e8d1d25244e79f428003d73f350c1bc2cc94c198f38dd23134a76e5e5450f7efa9c344453321d232a8a2e1

test:
  secret_key_base: 3395e37dae24da8a1154c8f4a6d26e4dd44457b07b540ef3d830d188c4c455f20b658dcc612986fc876101ab8e0e3a53eb40dce98de0ff052c0c5fdf5f1724d2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
